### ISSUE TITLE
当一张图片也没有的时候 在recyclerview 上好像会发生乱序的问题。

### ISSUE THREAD

**Issue by hunji66** [jeasonlzy/NineGridView#1]
我看 laobie/NineGridImageView 在1.0.1解决了这个问题。
不知道你是根据哪个版本修改的啊。。？

**Comment by jeasonlzy0216** [comment]
具体哪个版本我也不知道了。。但是目前是没有问题的。。我一直在用。。

**Comment by hunji66** [comment]
好像是我使用姿势的问题。已经ok了。
